/******************************************************************
 * COPYRIGHT (c) 2000 Denali Software, Inc.  All rights reserved. *
 * -------------------------------------------------------------- *
 * This code is proprietary and confidential information of       *
 * Denali Software. It may not be reproduced, used or transmitted *
 * in any form whatsoever without the express and written         *
 * permission of Denali Software.                                 *
 ******************************************************************
 * WARNING:  This file was automatically generated.  Manual
 * editing may result in undetermined behavior, and may be in
 * violation of the Denali Support Agreement.
 *****************************************************************/
 /* REL: mips.cambridge-MIPS_Roc-it_1_052506 */

#define MC_ADDR_PINS_ADDR                 5                    
#define MC_ADDR_PINS_OFFSET               24                   
#define MC_ADDR_PINS_WIDTH                3                    
#define MC_ADDRESS_WIDTH                  14                   
#define MC_AP_ADDR                        0                    
#define MC_AP_OFFSET                      0                    
#define MC_AP_WIDTH                       1                    
#define MC_APREBIT_ADDR                   8                    
#define MC_APREBIT_CS_WIDTH               4                    
#define MC_APREBIT_OFFSET                 8                    
#define MC_APREBIT_WIDTH                  4                    
#define MC_AREFRESH_ADDR                  0                    
#define MC_AREFRESH_OFFSET                8                    
#define MC_AREFRESH_WIDTH                 1                    
#define MC_AUTO_REFRESH_MODE_ADDR         0                    
#define MC_AUTO_REFRESH_MODE_OFFSET       16                   
#define MC_AUTO_REFRESH_MODE_WIDTH        1                    
#define MC_BANK_WIDTH                     2                    
#define MC_BSTLEN_WIDTH                   3                    
#define MC_BYTE_WIDTH                     (#MAX_BYTE_WORD+1)   
#define MC_CASLAT_ADDR                    6                    
#define MC_CASLAT_LIN_ADDR                10                   
#define MC_CASLAT_LIN_GATE_ADDR           10                   
#define MC_CASLAT_LIN_GATE_OFFSET         8                    
#define MC_CASLAT_LIN_GATE_WIDTH          5                    
#define MC_CASLAT_LIN_OFFSET              0                    
#define MC_CASLAT_LIN_WIDTH               5                    
#define MC_CASLAT_OFFSET                  0                    
#define MC_CASLAT_WIDTH                   3                    
#define MC_COLUMN_SIZE_ADDR               6                    
#define MC_COLUMN_SIZE_OFFSET             8                    
#define MC_COLUMN_SIZE_WIDTH              3                    
#define MC_CONCURRENTAP_ADDR              0                    
#define MC_CONCURRENTAP_OFFSET            24                   
#define MC_CONCURRENTAP_WIDTH             1                    
#define MC_CONTROL_WORD_WIDTH             13                   
#define MC_CS_BANK_WIDTH                  3                    
#define MC_CS_DIFF_WIDTH                  1                    
#define MC_CS_MAP_ADDR                    4                    
#define MC_CS_MAP_OFFSET                  24                   
#define MC_CS_MAP_WIDTH                   2                    
#define MC_CS_WIDTH                       1                    
#define MC_DATA_BYTE_WIDTH                4                    
#define MC_DATA_WIDTH                     64                   
#define MC_DLL_BYPASS_MODE_ADDR           1                    
#define MC_DLL_BYPASS_MODE_OFFSET         8                    
#define MC_DLL_BYPASS_MODE_WIDTH          1                    
#define MC_DLL_DQS_DELAY_0_ADDR           12                   
#define MC_DLL_DQS_DELAY_0_OFFSET         16                   
#define MC_DLL_DQS_DELAY_0_WIDTH          7                    
#define MC_DLL_DQS_DELAY_1_ADDR           12                   
#define MC_DLL_DQS_DELAY_1_OFFSET         24                   
#define MC_DLL_DQS_DELAY_1_WIDTH          7                    
#define MC_DLL_DQS_DELAY_2_ADDR           13                   
#define MC_DLL_DQS_DELAY_2_OFFSET         0                    
#define MC_DLL_DQS_DELAY_2_WIDTH          7                    
#define MC_DLL_DQS_DELAY_3_ADDR           13                   
#define MC_DLL_DQS_DELAY_3_OFFSET         8                    
#define MC_DLL_DQS_DELAY_3_WIDTH          7                    
#define MC_DLL_DQS_DELAY_4_ADDR           13                   
#define MC_DLL_DQS_DELAY_4_OFFSET         16                   
#define MC_DLL_DQS_DELAY_4_WIDTH          7                    
#define MC_DLL_DQS_DELAY_5_ADDR           13                   
#define MC_DLL_DQS_DELAY_5_OFFSET         24                   
#define MC_DLL_DQS_DELAY_5_WIDTH          7                    
#define MC_DLL_DQS_DELAY_6_ADDR           14                   
#define MC_DLL_DQS_DELAY_6_OFFSET         0                    
#define MC_DLL_DQS_DELAY_6_WIDTH          7                    
#define MC_DLL_DQS_DELAY_7_ADDR           14                   
#define MC_DLL_DQS_DELAY_7_OFFSET         8                    
#define MC_DLL_DQS_DELAY_7_WIDTH          7                    
#define MC_DLL_DQS_DELAY_BYPASS_0_ADDR    14                   
#define MC_DLL_DQS_DELAY_BYPASS_0_OFFSET  16                   
#define MC_DLL_DQS_DELAY_BYPASS_0_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_1_ADDR    14                   
#define MC_DLL_DQS_DELAY_BYPASS_1_OFFSET  24                   
#define MC_DLL_DQS_DELAY_BYPASS_1_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_2_ADDR    15                   
#define MC_DLL_DQS_DELAY_BYPASS_2_OFFSET  0                    
#define MC_DLL_DQS_DELAY_BYPASS_2_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_3_ADDR    15                   
#define MC_DLL_DQS_DELAY_BYPASS_3_OFFSET  8                    
#define MC_DLL_DQS_DELAY_BYPASS_3_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_4_ADDR    15                   
#define MC_DLL_DQS_DELAY_BYPASS_4_OFFSET  16                   
#define MC_DLL_DQS_DELAY_BYPASS_4_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_5_ADDR    15                   
#define MC_DLL_DQS_DELAY_BYPASS_5_OFFSET  24                   
#define MC_DLL_DQS_DELAY_BYPASS_5_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_6_ADDR    16                   
#define MC_DLL_DQS_DELAY_BYPASS_6_OFFSET  0                    
#define MC_DLL_DQS_DELAY_BYPASS_6_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_7_ADDR    16                   
#define MC_DLL_DQS_DELAY_BYPASS_7_OFFSET  8                    
#define MC_DLL_DQS_DELAY_BYPASS_7_WIDTH   7                    
#define MC_DLL_DQS_DELAY_BYPASS_WIDTH     7                    
#define MC_DLL_DQS_DELAY_WIDTH            7                    
#define MC_DLL_INCREMENT_ADDR             11                   
#define MC_DLL_INCREMENT_OFFSET           16                   
#define MC_DLL_INCREMENT_WIDTH            6                    
#define MC_DLL_LOCK_ADDR                  11                   
#define MC_DLL_LOCK_OFFSET                24                   
#define MC_DLL_LOCK_WIDTH                 6                    
#define MC_DLL_NUM_DELAYS_WIDTH           6                    
#define MC_DLL_START_POINT_ADDR           12                   
#define MC_DLL_START_POINT_OFFSET         0                    
#define MC_DLL_START_POINT_WIDTH          6                    
#define MC_DLLLOCKREG_ADDR                1                    
#define MC_DLLLOCKREG_OFFSET              0                    
#define MC_DLLLOCKREG_WIDTH               1                    
#define MC_DM_WIDTH                       8                    
#define MC_DQS_OUT_SHIFT_ADDR             16                   
#define MC_DQS_OUT_SHIFT_BYPASS_ADDR      16                   
#define MC_DQS_OUT_SHIFT_BYPASS_OFFSET    24                   
#define MC_DQS_OUT_SHIFT_BYPASS_WIDTH     7                    
#define MC_DQS_OUT_SHIFT_OFFSET           16                   
#define MC_DQS_OUT_SHIFT_WIDTH            7                    
#define MC_DQS_WIDTH                      8                    
#define MC_EFFECT_USER_DATA_WIDTH         128                  
#define MC_EMRS_DATA_ADDR                 19                   
#define MC_EMRS_DATA_OFFSET               0                    
#define MC_EMRS_DATA_WIDTH                14                   
#define MC_FAST_WRITE_ADDR                5                    
#define MC_FAST_WRITE_OFFSET              0                    
#define MC_FAST_WRITE_WIDTH               2                    
#define MC_INITAREF_ADDR                  8                    
#define MC_INITAREF_OFFSET                16                   
#define MC_INITAREF_WIDTH                 4                    
#define MC_INT_ACK_ADDR                   8                    
#define MC_INT_ACK_OFFSET                 24                   
#define MC_INT_ACK_WIDTH                  4                    
#define MC_INT_MASK_ADDR                  10                   
#define MC_INT_MASK_OFFSET                16                   
#define MC_INT_MASK_WIDTH                 5                    
#define MC_INT_STATUS_ADDR                10                   
#define MC_INT_STATUS_OFFSET              24                   
#define MC_INT_STATUS_WIDTH               5                    
#define MC_INTRPTAPBURST_ADDR             1                    
#define MC_INTRPTAPBURST_OFFSET           16                   
#define MC_INTRPTAPBURST_WIDTH            1                    
#define MC_INTRPTREADA_ADDR               1                    
#define MC_INTRPTREADA_OFFSET             24                   
#define MC_INTRPTREADA_WIDTH              1                    
#define MC_INTRPTWRITEA_ADDR              2                    
#define MC_INTRPTWRITEA_OFFSET            0                    
#define MC_INTRPTWRITEA_WIDTH             1                    
#define MC_MAX_ADDR_WIDTH                 32                   
#define MC_MAX_CMD_REG_WIDTH              43                   
#define MC_MAX_CMD_WIDTH                  3                    
#define MC_MAX_COL_REG_ADDR               9                    
#define MC_MAX_COL_REG_OFFSET             0                    
#define MC_MAX_COL_REG_WIDTH              4                    
#define MC_MAX_CS_REG_ADDR                5                    
#define MC_MAX_CS_REG_OFFSET              8                    
#define MC_MAX_CS_REG_WIDTH               2                    
#define MC_MAX_LEN_WIDTH                  6                    
#define MC_MAX_LEN_WORD_WIDTH             3                    
#define MC_MAX_REG_ADDR                   24                   
#define MC_MAX_ROW_REG_ADDR               9                    
#define MC_MAX_ROW_REG_OFFSET             8                    
#define MC_MAX_ROW_REG_WIDTH              4                    
#define MC_MAX_USER_ADDR_WIDTH            32                   
#define MC_NO_CMD_INIT_ADDR               2                    
#define MC_NO_CMD_INIT_OFFSET             8                    
#define MC_NO_CMD_INIT_WIDTH              1                    
#define MC_OUT_OF_RANGE_ADDR_ADDR         23                   
#define MC_OUT_OF_RANGE_ADDR_OFFSET       0                    
#define MC_OUT_OF_RANGE_ADDR_WIDTH        32                   
#define MC_OUT_OF_RANGE_LENGTH_ADDR       12                   
#define MC_OUT_OF_RANGE_LENGTH_OFFSET     8                    
#define MC_OUT_OF_RANGE_LENGTH_WIDTH      6                    
#define MC_OUT_OF_RANGE_TYPE_ADDR         6                    
#define MC_OUT_OF_RANGE_TYPE_OFFSET       16                   
#define MC_OUT_OF_RANGE_TYPE_WIDTH        3                    
#define MC_POWER_DOWN_ADDR                2                    
#define MC_POWER_DOWN_OFFSET              16                   
#define MC_POWER_DOWN_WIDTH               1                    
#define MC_Q_FULLNESS_ADDR                6                    
#define MC_Q_FULLNESS_OFFSET              24                   
#define MC_Q_FULLNESS_WIDTH               3                    
#define MC_RDLAT_WIDTH                    3                    
#define MC_READ_FIFO_DEPTH_WIDTH          3                    
#define MC_READFIFO_DATA_WIDTH            128                  
#define MC_REG_ADDR_WIDTH                 5                    
#define MC_REG_DATA_WIDTH                 32                   
#define MC_REG_DIMM_ENABLE_ADDR           2                    
#define MC_REG_DIMM_ENABLE_OFFSET         24                   
#define MC_REG_DIMM_ENABLE_WIDTH          1                    
#define MC_REG_MASK_WIDTH                 4                    
#define MC_SDR_MODE_ADDR                  3                    
#define MC_SDR_MODE_OFFSET                0                    
#define MC_SDR_MODE_WIDTH                 1                    
#define MC_SPLITCOL_WIDTH                 14                   
#define MC_SREFRESH_ADDR                  3                    
#define MC_SREFRESH_OFFSET                8                    
#define MC_SREFRESH_WIDTH                 1                    
#define MC_START_ADDR                     3                    
#define MC_START_OFFSET                   16                   
#define MC_START_WIDTH                    1                    
#define MC_STAT_WIDTH                     2                    
#define MC_TCKE_ADDR                      7                    
#define MC_TCKE_OFFSET                    0                    
#define MC_TCKE_WIDTH                     3                    
#define MC_TDAL_ADDR                      9                    
#define MC_TDAL_OFFSET                    16                   
#define MC_TDAL_WIDTH                     4                    
#define MC_TDLL_ADDR                      19                   
#define MC_TDLL_OFFSET                    16                   
#define MC_TDLL_WIDTH                     16                   
#define MC_TEMRS_ADDR                     5                    
#define MC_TEMRS_OFFSET                   16                   
#define MC_TEMRS_WIDTH                    2                    
#define MC_TINIT_ADDR                     22                   
#define MC_TINIT_OFFSET                   0                    
#define MC_TINIT_WIDTH                    24                   
#define MC_TMRD_ADDR                      11                   
#define MC_TMRD_OFFSET                    0                    
#define MC_TMRD_WIDTH                     5                    
#define MC_TPDEX_ADDR                     7                    
#define MC_TPDEX_OFFSET                   8                    
#define MC_TPDEX_WIDTH                    3                    
#define MC_TRAS_LOCKOUT_ADDR              3                    
#define MC_TRAS_LOCKOUT_OFFSET            24                   
#define MC_TRAS_LOCKOUT_WIDTH             1                    
#define MC_TRAS_MAX_ADDR                  20                   
#define MC_TRAS_MAX_OFFSET                0                    
#define MC_TRAS_MAX_WIDTH                 16                   
#define MC_TRAS_MIN_ADDR                  17                   
#define MC_TRAS_MIN_OFFSET                16                   
#define MC_TRAS_MIN_WIDTH                 8                    
#define MC_TRC_ADDR                       11                   
#define MC_TRC_OFFSET                     8                    
#define MC_TRC_WIDTH                      5                    
#define MC_TRCD_INT_ADDR                  17                   
#define MC_TRCD_INT_OFFSET                24                   
#define MC_TRCD_INT_WIDTH                 8                    
#define MC_TRCD_WIDTH                     8                    
#define MC_TREF_ADDR                      18                   
#define MC_TREF_ENABLE_ADDR               4                    
#define MC_TREF_ENABLE_OFFSET             0                    
#define MC_TREF_ENABLE_WIDTH              1                    
#define MC_TREF_OFFSET                    8                    
#define MC_TREF_WIDTH                     12                   
#define MC_TRFC_ADDR                      18                   
#define MC_TRFC_OFFSET                    0                    
#define MC_TRFC_WIDTH                     8                    
#define MC_TRP_ADDR                       9                    
#define MC_TRP_OFFSET                     24                   
#define MC_TRP_WIDTH                      4                    
#define MC_TRRD_ADDR                      7                    
#define MC_TRRD_OFFSET                    16                   
#define MC_TRRD_WIDTH                     3                    
#define MC_TWR_INT_ADDR                   7                    
#define MC_TWR_INT_OFFSET                 24                   
#define MC_TWR_INT_WIDTH                  3                    
#define MC_TWR_WIDTH                      3                    
#define MC_TWTR_ADDR                      8                    
#define MC_TWTR_OFFSET                    0                    
#define MC_TWTR_WIDTH                     3                    
#define MC_TXSNR_ADDR                     20                   
#define MC_TXSNR_OFFSET                   16                   
#define MC_TXSNR_WIDTH                    16                   
#define MC_TXSR_ADDR                      21                   
#define MC_TXSR_OFFSET                    0                    
#define MC_TXSR_WIDTH                     16                   
#define MC_TYPE_WIDTH                     3                    
#define MC_USER_DATA_WIDTH                128                  
#define MC_USER_MASK_WIDTH                16                   
#define MC_VERSION_ADDR                   21                   
#define MC_VERSION_OFFSET                 16                   
#define MC_VERSION_WIDTH                  16                   
#define MC_WR_DQS_SHIFT_ADDR              17                   
#define MC_WR_DQS_SHIFT_BYPASS_ADDR       17                   
#define MC_WR_DQS_SHIFT_BYPASS_OFFSET     8                    
#define MC_WR_DQS_SHIFT_BYPASS_WIDTH      7                    
#define MC_WR_DQS_SHIFT_OFFSET            0                    
#define MC_WR_DQS_SHIFT_WIDTH             7                    
#define MC_WRITE_FIFO_DEPTH_WIDTH         2                    
#define MC_WRITE_FIFO_SRAM_DEPTH_WIDTH    2                    
#define MC_WRITE_FIFO_STATUS_WIDTH        4                    
#define MC_WRITE_MODEREG_ADDR             4                    
#define MC_WRITE_MODEREG_OFFSET           16                   
#define MC_WRITE_MODEREG_WIDTH            1                    
#define MC_WRITEINTERP_ADDR               4                    
#define MC_WRITEINTERP_OFFSET             8                    
#define MC_WRITEINTERP_WIDTH              1                    
