/******************************************************************
 * COPYRIGHT (c) 2000 Denali Software, Inc.  All rights reserved. *
 * -------------------------------------------------------------- *
 * This code is proprietary and confidential information of       *
 * Denali Software. It may not be reproduced, used or transmitted *
 * in any form whatsoever without the express and written         *
 * permission of Denali Software.                                 *
 ******************************************************************
 * WARNING:  This file was automatically generated.  Manual
 * editing may result in undetermined behavior, and may be in
 * violation of the Denali Support Agreement.
 *****************************************************************/
 /* REL: mips.cambridge-MIPS_Roc-it_1_052506 */

#define ADDR_PINS_ADDR                 5                    
#define ADDR_PINS_OFFSET               24                   
#define ADDR_PINS_WIDTH                3                    
#define ADDRESS_WIDTH                  14                   
#define AP_ADDR                        0                    
#define AP_OFFSET                      0                    
#define AP_WIDTH                       1                    
#define APREBIT_ADDR                   8                    
#define APREBIT_CS_WIDTH               4                    
#define APREBIT_OFFSET                 8                    
#define APREBIT_WIDTH                  4                    
#define AREFRESH_ADDR                  0                    
#define AREFRESH_OFFSET                8                    
#define AREFRESH_WIDTH                 1                    
#define AUTO_REFRESH_MODE_ADDR         0                    
#define AUTO_REFRESH_MODE_OFFSET       16                   
#define AUTO_REFRESH_MODE_WIDTH        1                    
#define BANK_WIDTH                     2                    
#define BSTLEN_WIDTH                   3                    
#define BYTE_WIDTH                     (#MAX_BYTE_WORD+1)   
#define CASLAT_ADDR                    6                    
#define CASLAT_LIN_ADDR                10                   
#define CASLAT_LIN_GATE_ADDR           10                   
#define CASLAT_LIN_GATE_OFFSET         8                    
#define CASLAT_LIN_GATE_WIDTH          5                    
#define CASLAT_LIN_OFFSET              0                    
#define CASLAT_LIN_WIDTH               5                    
#define CASLAT_OFFSET                  0                    
#define CASLAT_WIDTH                   3                    
#define COLUMN_SIZE_ADDR               6                    
#define COLUMN_SIZE_OFFSET             8                    
#define COLUMN_SIZE_WIDTH              3                    
#define CONCURRENTAP_ADDR              0                    
#define CONCURRENTAP_OFFSET            24                   
#define CONCURRENTAP_WIDTH             1                    
#define CONTROL_WORD_WIDTH             13                   
#define CS_BANK_WIDTH                  3                    
#define CS_DIFF_WIDTH                  1                    
#define CS_MAP_ADDR                    4                    
#define CS_MAP_OFFSET                  24                   
#define CS_MAP_WIDTH                   2                    
#define CS_WIDTH                       1                    
#define DATA_BYTE_WIDTH                4                    
#define DATA_WIDTH                     64                   
#define DLL_BYPASS_MODE_ADDR           1                    
#define DLL_BYPASS_MODE_OFFSET         8                    
#define DLL_BYPASS_MODE_WIDTH          1                    
#define DLL_DQS_DELAY_0_ADDR           12                   
#define DLL_DQS_DELAY_0_OFFSET         16                   
#define DLL_DQS_DELAY_0_WIDTH          7                    
#define DLL_DQS_DELAY_1_ADDR           12                   
#define DLL_DQS_DELAY_1_OFFSET         24                   
#define DLL_DQS_DELAY_1_WIDTH          7                    
#define DLL_DQS_DELAY_2_ADDR           13                   
#define DLL_DQS_DELAY_2_OFFSET         0                    
#define DLL_DQS_DELAY_2_WIDTH          7                    
#define DLL_DQS_DELAY_3_ADDR           13                   
#define DLL_DQS_DELAY_3_OFFSET         8                    
#define DLL_DQS_DELAY_3_WIDTH          7                    
#define DLL_DQS_DELAY_4_ADDR           13                   
#define DLL_DQS_DELAY_4_OFFSET         16                   
#define DLL_DQS_DELAY_4_WIDTH          7                    
#define DLL_DQS_DELAY_5_ADDR           13                   
#define DLL_DQS_DELAY_5_OFFSET         24                   
#define DLL_DQS_DELAY_5_WIDTH          7                    
#define DLL_DQS_DELAY_6_ADDR           14                   
#define DLL_DQS_DELAY_6_OFFSET         0                    
#define DLL_DQS_DELAY_6_WIDTH          7                    
#define DLL_DQS_DELAY_7_ADDR           14                   
#define DLL_DQS_DELAY_7_OFFSET         8                    
#define DLL_DQS_DELAY_7_WIDTH          7                    
#define DLL_DQS_DELAY_BYPASS_0_ADDR    14                   
#define DLL_DQS_DELAY_BYPASS_0_OFFSET  16                   
#define DLL_DQS_DELAY_BYPASS_0_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_1_ADDR    14                   
#define DLL_DQS_DELAY_BYPASS_1_OFFSET  24                   
#define DLL_DQS_DELAY_BYPASS_1_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_2_ADDR    15                   
#define DLL_DQS_DELAY_BYPASS_2_OFFSET  0                    
#define DLL_DQS_DELAY_BYPASS_2_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_3_ADDR    15                   
#define DLL_DQS_DELAY_BYPASS_3_OFFSET  8                    
#define DLL_DQS_DELAY_BYPASS_3_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_4_ADDR    15                   
#define DLL_DQS_DELAY_BYPASS_4_OFFSET  16                   
#define DLL_DQS_DELAY_BYPASS_4_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_5_ADDR    15                   
#define DLL_DQS_DELAY_BYPASS_5_OFFSET  24                   
#define DLL_DQS_DELAY_BYPASS_5_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_6_ADDR    16                   
#define DLL_DQS_DELAY_BYPASS_6_OFFSET  0                    
#define DLL_DQS_DELAY_BYPASS_6_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_7_ADDR    16                   
#define DLL_DQS_DELAY_BYPASS_7_OFFSET  8                    
#define DLL_DQS_DELAY_BYPASS_7_WIDTH   7                    
#define DLL_DQS_DELAY_BYPASS_WIDTH     7                    
#define DLL_DQS_DELAY_WIDTH            7                    
#define DLL_INCREMENT_ADDR             11                   
#define DLL_INCREMENT_OFFSET           16                   
#define DLL_INCREMENT_WIDTH            6                    
#define DLL_LOCK_ADDR                  11                   
#define DLL_LOCK_OFFSET                24                   
#define DLL_LOCK_WIDTH                 6                    
#define DLL_NUM_DELAYS_WIDTH           6                    
#define DLL_START_POINT_ADDR           12                   
#define DLL_START_POINT_OFFSET         0                    
#define DLL_START_POINT_WIDTH          6                    
#define DLLLOCKREG_ADDR                1                    
#define DLLLOCKREG_OFFSET              0                    
#define DLLLOCKREG_WIDTH               1                    
#define DM_WIDTH                       8                    
#define DQS_OUT_SHIFT_ADDR             16                   
#define DQS_OUT_SHIFT_BYPASS_ADDR      16                   
#define DQS_OUT_SHIFT_BYPASS_OFFSET    24                   
#define DQS_OUT_SHIFT_BYPASS_WIDTH     7                    
#define DQS_OUT_SHIFT_OFFSET           16                   
#define DQS_OUT_SHIFT_WIDTH            7                    
#define DQS_WIDTH                      8                    
#define EFFECT_USER_DATA_WIDTH         128                  
#define EMRS_DATA_ADDR                 19                   
#define EMRS_DATA_OFFSET               0                    
#define EMRS_DATA_WIDTH                14                   
#define FAST_WRITE_ADDR                5                    
#define FAST_WRITE_OFFSET              0                    
#define FAST_WRITE_WIDTH               2                    
#define INITAREF_ADDR                  8                    
#define INITAREF_OFFSET                16                   
#define INITAREF_WIDTH                 4                    
#define INT_ACK_ADDR                   8                    
#define INT_ACK_OFFSET                 24                   
#define INT_ACK_WIDTH                  4                    
#define INT_MASK_ADDR                  10                   
#define INT_MASK_OFFSET                16                   
#define INT_MASK_WIDTH                 5                    
#define INT_STATUS_ADDR                10                   
#define INT_STATUS_OFFSET              24                   
#define INT_STATUS_WIDTH               5                    
#define INTRPTAPBURST_ADDR             1                    
#define INTRPTAPBURST_OFFSET           16                   
#define INTRPTAPBURST_WIDTH            1                    
#define INTRPTREADA_ADDR               1                    
#define INTRPTREADA_OFFSET             24                   
#define INTRPTREADA_WIDTH              1                    
#define INTRPTWRITEA_ADDR              2                    
#define INTRPTWRITEA_OFFSET            0                    
#define INTRPTWRITEA_WIDTH             1                    
#define MAX_ADDR_WIDTH                 32                   
#define MAX_CMD_REG_WIDTH              43                   
#define MAX_CMD_WIDTH                  3                    
#define MAX_COL_REG_ADDR               9                    
#define MAX_COL_REG_OFFSET             0                    
#define MAX_COL_REG_WIDTH              4                    
#define MAX_CS_REG_ADDR                5                    
#define MAX_CS_REG_OFFSET              8                    
#define MAX_CS_REG_WIDTH               2                    
#define MAX_LEN_WIDTH                  6                    
#define MAX_LEN_WORD_WIDTH             3                    
#define MAX_REG_ADDR                   24                   
#define MAX_ROW_REG_ADDR               9                    
#define MAX_ROW_REG_OFFSET             8                    
#define MAX_ROW_REG_WIDTH              4                    
#define MAX_USER_ADDR_WIDTH            32                   
#define NO_CMD_INIT_ADDR               2                    
#define NO_CMD_INIT_OFFSET             8                    
#define NO_CMD_INIT_WIDTH              1                    
#define OUT_OF_RANGE_ADDR_ADDR         23                   
#define OUT_OF_RANGE_ADDR_OFFSET       0                    
#define OUT_OF_RANGE_ADDR_WIDTH        32                   
#define OUT_OF_RANGE_LENGTH_ADDR       12                   
#define OUT_OF_RANGE_LENGTH_OFFSET     8                    
#define OUT_OF_RANGE_LENGTH_WIDTH      6                    
#define OUT_OF_RANGE_TYPE_ADDR         6                    
#define OUT_OF_RANGE_TYPE_OFFSET       16                   
#define OUT_OF_RANGE_TYPE_WIDTH        3                    
#define POWER_DOWN_ADDR                2                    
#define POWER_DOWN_OFFSET              16                   
#define POWER_DOWN_WIDTH               1                    
#define Q_FULLNESS_ADDR                6                    
#define Q_FULLNESS_OFFSET              24                   
#define Q_FULLNESS_WIDTH               3                    
#define RDLAT_WIDTH                    3                    
#define READ_FIFO_DEPTH_WIDTH          3                    
#define READFIFO_DATA_WIDTH            128                  
#define REG_ADDR_WIDTH                 5                    
#define REG_DATA_WIDTH                 32                   
#define REG_DIMM_ENABLE_ADDR           2                    
#define REG_DIMM_ENABLE_OFFSET         24                   
#define REG_DIMM_ENABLE_WIDTH          1                    
#define REG_MASK_WIDTH                 4                    
#define SDR_MODE_ADDR                  3                    
#define SDR_MODE_OFFSET                0                    
#define SDR_MODE_WIDTH                 1                    
#define SPLITCOL_WIDTH                 14                   
#define SREFRESH_ADDR                  3                    
#define SREFRESH_OFFSET                8                    
#define SREFRESH_WIDTH                 1                    
#define START_ADDR                     3                    
#define START_OFFSET                   16                   
#define START_WIDTH                    1                    
#define STAT_WIDTH                     2                    
#define TCKE_ADDR                      7                    
#define TCKE_OFFSET                    0                    
#define TCKE_WIDTH                     3                    
#define TDAL_ADDR                      9                    
#define TDAL_OFFSET                    16                   
#define TDAL_WIDTH                     4                    
#define TDLL_ADDR                      19                   
#define TDLL_OFFSET                    16                   
#define TDLL_WIDTH                     16                   
#define TEMRS_ADDR                     5                    
#define TEMRS_OFFSET                   16                   
#define TEMRS_WIDTH                    2                    
#define TINIT_ADDR                     22                   
#define TINIT_OFFSET                   0                    
#define TINIT_WIDTH                    24                   
#define TMRD_ADDR                      11                   
#define TMRD_OFFSET                    0                    
#define TMRD_WIDTH                     5                    
#define TPDEX_ADDR                     7                    
#define TPDEX_OFFSET                   8                    
#define TPDEX_WIDTH                    3                    
#define TRAS_LOCKOUT_ADDR              3                    
#define TRAS_LOCKOUT_OFFSET            24                   
#define TRAS_LOCKOUT_WIDTH             1                    
#define TRAS_MAX_ADDR                  20                   
#define TRAS_MAX_OFFSET                0                    
#define TRAS_MAX_WIDTH                 16                   
#define TRAS_MIN_ADDR                  17                   
#define TRAS_MIN_OFFSET                16                   
#define TRAS_MIN_WIDTH                 8                    
#define TRC_ADDR                       11                   
#define TRC_OFFSET                     8                    
#define TRC_WIDTH                      5                    
#define TRCD_INT_ADDR                  17                   
#define TRCD_INT_OFFSET                24                   
#define TRCD_INT_WIDTH                 8                    
#define TRCD_WIDTH                     8                    
#define TREF_ADDR                      18                   
#define TREF_ENABLE_ADDR               4                    
#define TREF_ENABLE_OFFSET             0                    
#define TREF_ENABLE_WIDTH              1                    
#define TREF_OFFSET                    8                    
#define TREF_WIDTH                     12                   
#define TRFC_ADDR                      18                   
#define TRFC_OFFSET                    0                    
#define TRFC_WIDTH                     8                    
#define TRP_ADDR                       9                    
#define TRP_OFFSET                     24                   
#define TRP_WIDTH                      4                    
#define TRRD_ADDR                      7                    
#define TRRD_OFFSET                    16                   
#define TRRD_WIDTH                     3                    
#define TWR_INT_ADDR                   7                    
#define TWR_INT_OFFSET                 24                   
#define TWR_INT_WIDTH                  3                    
#define TWR_WIDTH                      3                    
#define TWTR_ADDR                      8                    
#define TWTR_OFFSET                    0                    
#define TWTR_WIDTH                     3                    
#define TXSNR_ADDR                     20                   
#define TXSNR_OFFSET                   16                   
#define TXSNR_WIDTH                    16                   
#define TXSR_ADDR                      21                   
#define TXSR_OFFSET                    0                    
#define TXSR_WIDTH                     16                   
#define TYPE_WIDTH                     3                    
#define USER_DATA_WIDTH                128                  
#define USER_MASK_WIDTH                16                   
#define VERSION_ADDR                   21                   
#define VERSION_OFFSET                 16                   
#define VERSION_WIDTH                  16                   
#define WR_DQS_SHIFT_ADDR              17                   
#define WR_DQS_SHIFT_BYPASS_ADDR       17                   
#define WR_DQS_SHIFT_BYPASS_OFFSET     8                    
#define WR_DQS_SHIFT_BYPASS_WIDTH      7                    
#define WR_DQS_SHIFT_OFFSET            0                    
#define WR_DQS_SHIFT_WIDTH             7                    
#define WRITE_FIFO_DEPTH_WIDTH         2                    
#define WRITE_FIFO_SRAM_DEPTH_WIDTH    2                    
#define WRITE_FIFO_STATUS_WIDTH        4                    
#define WRITE_MODEREG_ADDR             4                    
#define WRITE_MODEREG_OFFSET           16                   
#define WRITE_MODEREG_WIDTH            1                    
#define WRITEINTERP_ADDR               4                    
#define WRITEINTERP_OFFSET             8                    
#define WRITEINTERP_WIDTH              1                    
